package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private short codigoBairro;
     private String bairro;
     private Set eventoses = new HashSet(0);
     private Set ocorrenciases = new HashSet(0);

    public Bairro() {
    }

	
    public Bairro(short codigoBairro, String bairro) {
        this.codigoBairro = codigoBairro;
        this.bairro = bairro;
    }
    public Bairro(short codigoBairro, String bairro, Set eventoses, Set ocorrenciases) {
       this.codigoBairro = codigoBairro;
       this.bairro = bairro;
       this.eventoses = eventoses;
       this.ocorrenciases = ocorrenciases;
    }
   
    public short getCodigoBairro() {
        return this.codigoBairro;
    }
    
    public void setCodigoBairro(short codigoBairro) {
        this.codigoBairro = codigoBairro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public Set getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set eventoses) {
        this.eventoses = eventoses;
    }
    public Set getOcorrenciases() {
        return this.ocorrenciases;
    }
    
    public void setOcorrenciases(Set ocorrenciases) {
        this.ocorrenciases = ocorrenciases;
    }




}


