package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EventosId generated by hbm2java
 */
public class EventosId  implements java.io.Serializable {


     private String tipoEvento;
     private Date dataHoraInicio;

    public EventosId() {
    }

    public EventosId(String tipoEvento, Date dataHoraInicio) {
       this.tipoEvento = tipoEvento;
       this.dataHoraInicio = dataHoraInicio;
    }
   
    public String getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }
    public Date getDataHoraInicio() {
        return this.dataHoraInicio;
    }
    
    public void setDataHoraInicio(Date dataHoraInicio) {
        this.dataHoraInicio = dataHoraInicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventosId) ) return false;
		 EventosId castOther = ( EventosId ) other; 
         
		 return ( (this.getTipoEvento()==castOther.getTipoEvento()) || ( this.getTipoEvento()!=null && castOther.getTipoEvento()!=null && this.getTipoEvento().equals(castOther.getTipoEvento()) ) )
 && ( (this.getDataHoraInicio()==castOther.getDataHoraInicio()) || ( this.getDataHoraInicio()!=null && castOther.getDataHoraInicio()!=null && this.getDataHoraInicio().equals(castOther.getDataHoraInicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipoEvento() == null ? 0 : this.getTipoEvento().hashCode() );
         result = 37 * result + ( getDataHoraInicio() == null ? 0 : this.getDataHoraInicio().hashCode() );
         return result;
   }   


}


