package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Eventos generated by hbm2java
 */
public class Eventos  implements java.io.Serializable {


     private EventosId id;
     private Bairro bairro;
     private Logradouro logradouro;
     private Date dataHoraTermino;
     private boolean removido;

    public Eventos() {
    }

    public Eventos(EventosId id, Bairro bairro, Logradouro logradouro, Date dataHoraTermino, boolean removido) {
       this.id = id;
       this.bairro = bairro;
       this.logradouro = logradouro;
       this.dataHoraTermino = dataHoraTermino;
       this.removido = removido;
    }
   
    public EventosId getId() {
        return this.id;
    }
    
    public void setId(EventosId id) {
        this.id = id;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public Logradouro getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Logradouro logradouro) {
        this.logradouro = logradouro;
    }
    public Date getDataHoraTermino() {
        return this.dataHoraTermino;
    }
    
    public void setDataHoraTermino(Date dataHoraTermino) {
        this.dataHoraTermino = dataHoraTermino;
    }
    public boolean isRemovido() {
        return this.removido;
    }
    
    public void setRemovido(boolean removido) {
        this.removido = removido;
    }




}


