package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer codigoLog;
     private Policial policial;
     private Date dataHora;
     private String local;
     private String operacao;

    public Log() {
    }

	
    public Log(Policial policial, Date dataHora, String local) {
        this.policial = policial;
        this.dataHora = dataHora;
        this.local = local;
    }
    public Log(Policial policial, Date dataHora, String local, String operacao) {
       this.policial = policial;
       this.dataHora = dataHora;
       this.local = local;
       this.operacao = operacao;
    }
   
    public Integer getCodigoLog() {
        return this.codigoLog;
    }
    
    public void setCodigoLog(Integer codigoLog) {
        this.codigoLog = codigoLog;
    }
    public Policial getPolicial() {
        return this.policial;
    }
    
    public void setPolicial(Policial policial) {
        this.policial = policial;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(String operacao) {
        this.operacao = operacao;
    }




}


