package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Logradouro generated by hbm2java
 */
public class Logradouro  implements java.io.Serializable {


     private short codigoLogradouro;
     private String logradouro;
     private String tipo;
     private Set ocorrenciases = new HashSet(0);
     private Set eventoses = new HashSet(0);

    public Logradouro() {
    }

	
    public Logradouro(short codigoLogradouro, String logradouro, String tipo) {
        this.codigoLogradouro = codigoLogradouro;
        this.logradouro = logradouro;
        this.tipo = tipo;
    }
    public Logradouro(short codigoLogradouro, String logradouro, String tipo, Set ocorrenciases, Set eventoses) {
       this.codigoLogradouro = codigoLogradouro;
       this.logradouro = logradouro;
       this.tipo = tipo;
       this.ocorrenciases = ocorrenciases;
       this.eventoses = eventoses;
    }
   
    public short getCodigoLogradouro() {
        return this.codigoLogradouro;
    }
    
    public void setCodigoLogradouro(short codigoLogradouro) {
        this.codigoLogradouro = codigoLogradouro;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getOcorrenciases() {
        return this.ocorrenciases;
    }
    
    public void setOcorrenciases(Set ocorrenciases) {
        this.ocorrenciases = ocorrenciases;
    }
    public Set getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set eventoses) {
        this.eventoses = eventoses;
    }




}


