package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ocorrencias generated by hbm2java
 */
public class Ocorrencias  implements java.io.Serializable {


     private int numeroOcorrencia;
     private Policial policialByNumeroPolicial;
     private Natureza natureza;
     private Bairro bairro;
     private Turno turno;
     private Policial policialByRadioOperador;
     private Logradouro logradouro;
     private Date dataHoraAcionamento;
     private String numeroReds;
     private String nomeSolicitante;
     private String sinteseFato;
     private short numero;
     private String pontoReferencia;
     private String setor;
     private Date dataHoraChegadaLocal;
     private Date dataHoraEncerramento;
     private String presosApreendidos;
     private boolean removido;

    public Ocorrencias() {
    }

	
    public Ocorrencias(int numeroOcorrencia, Policial policialByNumeroPolicial, Natureza natureza, Bairro bairro, Turno turno, Policial policialByRadioOperador, Logradouro logradouro, Date dataHoraAcionamento, String numeroReds, String sinteseFato, short numero, String setor, Date dataHoraChegadaLocal, Date dataHoraEncerramento, boolean removido) {
        this.numeroOcorrencia = numeroOcorrencia;
        this.policialByNumeroPolicial = policialByNumeroPolicial;
        this.natureza = natureza;
        this.bairro = bairro;
        this.turno = turno;
        this.policialByRadioOperador = policialByRadioOperador;
        this.logradouro = logradouro;
        this.dataHoraAcionamento = dataHoraAcionamento;
        this.numeroReds = numeroReds;
        this.sinteseFato = sinteseFato;
        this.numero = numero;
        this.setor = setor;
        this.dataHoraChegadaLocal = dataHoraChegadaLocal;
        this.dataHoraEncerramento = dataHoraEncerramento;
        this.removido = removido;
    }
    public Ocorrencias(int numeroOcorrencia, Policial policialByNumeroPolicial, Natureza natureza, Bairro bairro, Turno turno, Policial policialByRadioOperador, Logradouro logradouro, Date dataHoraAcionamento, String numeroReds, String nomeSolicitante, String sinteseFato, short numero, String pontoReferencia, String setor, Date dataHoraChegadaLocal, Date dataHoraEncerramento, String presosApreendidos, boolean removido) {
       this.numeroOcorrencia = numeroOcorrencia;
       this.policialByNumeroPolicial = policialByNumeroPolicial;
       this.natureza = natureza;
       this.bairro = bairro;
       this.turno = turno;
       this.policialByRadioOperador = policialByRadioOperador;
       this.logradouro = logradouro;
       this.dataHoraAcionamento = dataHoraAcionamento;
       this.numeroReds = numeroReds;
       this.nomeSolicitante = nomeSolicitante;
       this.sinteseFato = sinteseFato;
       this.numero = numero;
       this.pontoReferencia = pontoReferencia;
       this.setor = setor;
       this.dataHoraChegadaLocal = dataHoraChegadaLocal;
       this.dataHoraEncerramento = dataHoraEncerramento;
       this.presosApreendidos = presosApreendidos;
       this.removido = removido;
    }
   
    public int getNumeroOcorrencia() {
        return this.numeroOcorrencia;
    }
    
    public void setNumeroOcorrencia(int numeroOcorrencia) {
        this.numeroOcorrencia = numeroOcorrencia;
    }
    public Policial getPolicialByNumeroPolicial() {
        return this.policialByNumeroPolicial;
    }
    
    public void setPolicialByNumeroPolicial(Policial policialByNumeroPolicial) {
        this.policialByNumeroPolicial = policialByNumeroPolicial;
    }
    public Natureza getNatureza() {
        return this.natureza;
    }
    
    public void setNatureza(Natureza natureza) {
        this.natureza = natureza;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Policial getPolicialByRadioOperador() {
        return this.policialByRadioOperador;
    }
    
    public void setPolicialByRadioOperador(Policial policialByRadioOperador) {
        this.policialByRadioOperador = policialByRadioOperador;
    }
    public Logradouro getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Logradouro logradouro) {
        this.logradouro = logradouro;
    }
    public Date getDataHoraAcionamento() {
        return this.dataHoraAcionamento;
    }
    
    public void setDataHoraAcionamento(Date dataHoraAcionamento) {
        this.dataHoraAcionamento = dataHoraAcionamento;
    }
    public String getNumeroReds() {
        return this.numeroReds;
    }
    
    public void setNumeroReds(String numeroReds) {
        this.numeroReds = numeroReds;
    }
    public String getNomeSolicitante() {
        return this.nomeSolicitante;
    }
    
    public void setNomeSolicitante(String nomeSolicitante) {
        this.nomeSolicitante = nomeSolicitante;
    }
    public String getSinteseFato() {
        return this.sinteseFato;
    }
    
    public void setSinteseFato(String sinteseFato) {
        this.sinteseFato = sinteseFato;
    }
    public short getNumero() {
        return this.numero;
    }
    
    public void setNumero(short numero) {
        this.numero = numero;
    }
    public String getPontoReferencia() {
        return this.pontoReferencia;
    }
    
    public void setPontoReferencia(String pontoReferencia) {
        this.pontoReferencia = pontoReferencia;
    }
    public String getSetor() {
        return this.setor;
    }
    
    public void setSetor(String setor) {
        this.setor = setor;
    }
    public Date getDataHoraChegadaLocal() {
        return this.dataHoraChegadaLocal;
    }
    
    public void setDataHoraChegadaLocal(Date dataHoraChegadaLocal) {
        this.dataHoraChegadaLocal = dataHoraChegadaLocal;
    }
    public Date getDataHoraEncerramento() {
        return this.dataHoraEncerramento;
    }
    
    public void setDataHoraEncerramento(Date dataHoraEncerramento) {
        this.dataHoraEncerramento = dataHoraEncerramento;
    }
    public String getPresosApreendidos() {
        return this.presosApreendidos;
    }
    
    public void setPresosApreendidos(String presosApreendidos) {
        this.presosApreendidos = presosApreendidos;
    }
    public boolean isRemovido() {
        return this.removido;
    }
    
    public void setRemovido(boolean removido) {
        this.removido = removido;
    }




}


