package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Policial generated by hbm2java
 */
public class Policial  implements java.io.Serializable {


     private int matricula;
     private String nome;
     private String postoGraduacao;
     private String tipoPermissao;
     private String endereco;
     private String status;
     private String email;
     private String senha;
     private boolean removida;
     private Set ocorrenciasesForRadioOperador = new HashSet(0);
     private Set logs = new HashSet(0);
     private Set telefones = new HashSet(0);
     private Set ocorrenciasesForNumeroPolicial = new HashSet(0);

    public Policial() {
    }

	
    public Policial(int matricula, String nome, String postoGraduacao, String tipoPermissao, String endereco, String email, String senha, boolean removida) {
        this.matricula = matricula;
        this.nome = nome;
        this.postoGraduacao = postoGraduacao;
        this.tipoPermissao = tipoPermissao;
        this.endereco = endereco;
        this.email = email;
        this.senha = senha;
        this.removida = removida;
    }
    public Policial(int matricula, String nome, String postoGraduacao, String tipoPermissao, String endereco, String status, String email, String senha, boolean removida, Set ocorrenciasesForRadioOperador, Set logs, Set telefones, Set ocorrenciasesForNumeroPolicial) {
       this.matricula = matricula;
       this.nome = nome;
       this.postoGraduacao = postoGraduacao;
       this.tipoPermissao = tipoPermissao;
       this.endereco = endereco;
       this.status = status;
       this.email = email;
       this.senha = senha;
       this.removida = removida;
       this.ocorrenciasesForRadioOperador = ocorrenciasesForRadioOperador;
       this.logs = logs;
       this.telefones = telefones;
       this.ocorrenciasesForNumeroPolicial = ocorrenciasesForNumeroPolicial;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getPostoGraduacao() {
        return this.postoGraduacao;
    }
    
    public void setPostoGraduacao(String postoGraduacao) {
        this.postoGraduacao = postoGraduacao;
    }
    public String getTipoPermissao() {
        return this.tipoPermissao;
    }
    
    public void setTipoPermissao(String tipoPermissao) {
        this.tipoPermissao = tipoPermissao;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public boolean isRemovida() {
        return this.removida;
    }
    
    public void setRemovida(boolean removida) {
        this.removida = removida;
    }
    public Set getOcorrenciasesForRadioOperador() {
        return this.ocorrenciasesForRadioOperador;
    }
    
    public void setOcorrenciasesForRadioOperador(Set ocorrenciasesForRadioOperador) {
        this.ocorrenciasesForRadioOperador = ocorrenciasesForRadioOperador;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Set telefones) {
        this.telefones = telefones;
    }
    public Set getOcorrenciasesForNumeroPolicial() {
        return this.ocorrenciasesForNumeroPolicial;
    }
    
    public void setOcorrenciasesForNumeroPolicial(Set ocorrenciasesForNumeroPolicial) {
        this.ocorrenciasesForNumeroPolicial = ocorrenciasesForNumeroPolicial;
    }




}


