package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA



/**
 * Telefone generated by hbm2java
 */
public class Telefone  implements java.io.Serializable {


     private TelefoneId id;
     private Policial policial;

    public Telefone() {
    }

    public Telefone(TelefoneId id, Policial policial) {
       this.id = id;
       this.policial = policial;
    }
   
    public TelefoneId getId() {
        return this.id;
    }
    
    public void setId(TelefoneId id) {
        this.id = id;
    }
    public Policial getPolicial() {
        return this.policial;
    }
    
    public void setPolicial(Policial policial) {
        this.policial = policial;
    }




}


