package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA



/**
 * TelefoneId generated by hbm2java
 */
public class TelefoneId  implements java.io.Serializable {


     private int matricula;
     private int telefone;

    public TelefoneId() {
    }

    public TelefoneId(int matricula, int telefone) {
       this.matricula = matricula;
       this.telefone = telefone;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public int getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(int telefone) {
        this.telefone = telefone;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefoneId) ) return false;
		 TelefoneId castOther = ( TelefoneId ) other; 
         
		 return (this.getMatricula()==castOther.getMatricula())
 && (this.getTelefone()==castOther.getTelefone());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMatricula();
         result = 37 * result + this.getTelefone();
         return result;
   }   


}


