package model;
// Generated 18/06/2013 01:20:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private short periodo;
     private String intervalo;
     private String turno;
     private Set ocorrenciases = new HashSet(0);

    public Turno() {
    }

	
    public Turno(short periodo, String intervalo, String turno) {
        this.periodo = periodo;
        this.intervalo = intervalo;
        this.turno = turno;
    }
    public Turno(short periodo, String intervalo, String turno, Set ocorrenciases) {
       this.periodo = periodo;
       this.intervalo = intervalo;
       this.turno = turno;
       this.ocorrenciases = ocorrenciases;
    }
   
    public short getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(short periodo) {
        this.periodo = periodo;
    }
    public String getIntervalo() {
        return this.intervalo;
    }
    
    public void setIntervalo(String intervalo) {
        this.intervalo = intervalo;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }
    public Set getOcorrenciases() {
        return this.ocorrenciases;
    }
    
    public void setOcorrenciases(Set ocorrenciases) {
        this.ocorrenciases = ocorrenciases;
    }




}


